Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 02/09/2020
Var
// Seção de Declarações das variáveis 
A, B, C =int

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
    Escreva("Digite o raio")
    Leia(A)
    Escreva("Digite a Altura")
    Leia(B)
    C <- (A*2)+ B

Fimalgoritmo